### ISSUE TITLE
Missing Chunk problem

### ISSUE THREAD

**Issue by fd-Joker** [voxel/voxel-example#11]
I entered this URL to see the example.
http://voxel.github.io/voxel-example/
However, no blocks are rendered.
I opened Javascript Console only to get missingChunk error.

**Comment by deathcap** [comment]
@fd-Joker The resource pack link went dead, fixed in https://github.com/voxel/voxel-example/commit/6c34f67076427b4ca8fbc67b89d3bcecdd53e213 - http://voxel.github.io/voxel-example/ should now render the bedrock blocks
