### ISSUE TITLE
Top right menu not accessible, click is intercepted by the mouselock

### ISSUE THREAD

**Issue by kumavis** [voxel/voxel-example#3]
Hey, enjoyed the blog post! thanks for that!

I can't use the top right menu, my click is intercepted by the mouselock
also getting this error in the console:
`no such plugin loaded to enable:  undefined voxel-debug`

**Comment by deathcap** [comment]
Thanks!

I've since greatly simplified voxel-example, it no longer has a datgui menu or voxel-debug (plugins not installed - trying to cut the dependencies significantly in voxel-example, it only comes with two non-built-in plugins). Can you repro on https://github.com/deathcap/voxelmetaverse?
